/**
 * Create slice simulation data — U2.3.
 *
 * Document structures, deck skeletons, the four visual demo variants, the
 * variant shortlists, version record builders, and edge-state presets. No
 * React, no fetch, no randomness, no clock: the same inputs always produce the
 * same structure, variants, draft, and version lineage, and every visual is a
 * local demo asset that was never generated by a model.
 */

export * from "./documents";
export * from "./decks";
export * from "./visuals";
export * from "./variants";
export * from "./versions";
export * from "./presets";
