"use client";

import { useEffect, useState } from "react";
import * as Dialog from "@radix-ui/react-dialog";
import { Bell, Check, ChevronLeft, ChevronRight, Database, Download, Eye, EyeOff, FileClock, KeyRound, Languages, Link2, LockKeyhole, Plus, Save, Settings2, ShieldCheck, Trash2, UserRound, Users, Webhook, X } from "lucide-react";
import { Badge } from "@nasaq/ui";
import type { Locale } from "@nasaq/contracts";
import { DemoToast } from "@/components/domain/operations/shared";

type SettingsSection = "profile" | "preferences" | "workspace" | "providers" | "integrations" | "data" | "audit";

function SettingToggle({ checked, onChange, label, detail }: { checked: boolean; onChange: (checked: boolean) => void; label: string; detail: string }) {
  return <label className="setting-toggle"><span><strong>{label}</strong><small>{detail}</small></span><input type="checkbox" checked={checked} onChange={(event) => onChange(event.target.checked)} /><span className="switch-visual" aria-hidden="true"><span /></span></label>;
}

export function SettingsPrototype({ locale }: { locale: Locale }) {
  const ar = locale === "ar";
  const [section, setSection] = useState<SettingsSection>("profile");
  const [notice, setNotice] = useState("");
  const [providerOpen, setProviderOpen] = useState(false);
  const [provider, setProvider] = useState("Northstar");
  const [keyValue, setKeyValue] = useState("");
  const [showKey, setShowKey] = useState(false);
  const [credentialAdded, setCredentialAdded] = useState(false);
  const [weeklyDigest, setWeeklyDigest] = useState(true);
  const [approvalAlerts, setApprovalAlerts] = useState(true);
  const [denseMode, setDenseMode] = useState(false);
  const DirectionIcon = ar ? ChevronLeft : ChevronRight;
  useEffect(() => { if (!notice) return; const timer = window.setTimeout(() => setNotice(""), 2800); return () => window.clearTimeout(timer); }, [notice]);
  const sections: Array<[SettingsSection, string, string, typeof UserRound]> = [
    ["profile", ar ? "الملف الشخصي" : "Profile", ar ? "الاسم والحساب" : "Name and account", UserRound],
    ["preferences", ar ? "التفضيلات" : "Preferences", ar ? "اللغة والكثافة والتنبيهات" : "Language, density, alerts", Languages],
    ["workspace", ar ? "مساحة العمل" : "Workspace", ar ? "الاسم والسياسات" : "Name and policies", Users],
    ["providers", ar ? "مفاتيح المزودين" : "Provider keys", ar ? "BYOK آمن ومحدود" : "Safe, scoped BYOK", KeyRound],
    ["integrations", ar ? "التكاملات" : "Integrations", ar ? "اتصالات خارجية" : "External connections", Link2],
    ["data", ar ? "البيانات والخصوصية" : "Data and privacy", ar ? "التصدير والاحتفاظ" : "Export and retention", Database],
    ["audit", ar ? "سجل التدقيق" : "Audit log", ar ? "أحداث السلطة" : "Authority events", FileClock],
  ];
  const integrations: Array<{ name: string; detail: string; connected: boolean; icon: typeof Bell }> = [
    { name: "Slack", detail: ar ? "إشعارات الفريق وطلبات الموافقة" : "Team alerts and approval requests", connected: true, icon: Webhook },
    { name: "Google Drive", detail: ar ? "قراءة ملفات ضمن مجلدات محددة" : "Read files from selected folders", connected: true, icon: Database },
    { name: "Email", detail: ar ? "إرسال ملخصات بعد موافقة بشرية" : "Send digests after human approval", connected: false, icon: Bell },
  ];
  function saved(message: string) { setNotice(message); }

  return <div className="ops-page settings-page"><header className="page-header"><div className="page-header__copy"><p className="page-eyebrow">{ar ? "سياسات المساحة" : "Workspace policy"}</p><h1 className="page-title">{ar ? "الإعدادات" : "Settings"}</h1><p className="page-description">{ar ? "اضبط الحساب والسياسات والمزودين والخصوصية دون إخفاء الأثر أو الصلاحية المطلوبة." : "Configure account, policy, providers, and privacy without hiding impact or required authority."}</p></div></header><div className="settings-layout"><aside className="settings-nav"><p>{ar ? "إعدادات فريق أفق" : "Horizon Team settings"}</p><nav aria-label={ar ? "أقسام الإعدادات" : "Settings sections"}>{sections.map(([id, label, detail, Icon]) => <button key={id} type="button" className={section === id ? "is-active" : ""} aria-current={section === id ? "page" : undefined} onClick={() => setSection(id)}><Icon size={16} /><span><strong>{label}</strong><small>{detail}</small></span><DirectionIcon size={13} /></button>)}</nav></aside><main className="settings-content">
    {section === "profile" ? <section className="settings-section"><div className="settings-section__head"><span><UserRound size={19} /></span><div><h2>{ar ? "الملف الشخصي" : "Profile"}</h2><p>{ar ? "الهوية التي تظهر في القرارات وسجلات التدقيق." : "The identity shown in decisions and audit records."}</p></div></div><div className="profile-settings-grid"><div className="profile-photo"><span>س</span><button className="button button--outline button--compact" type="button">{ar ? "تغيير الصورة" : "Change photo"}</button><small>{ar ? "PNG أو JPG · حتى ٢ م.ب" : "PNG or JPG · up to 2 MB"}</small></div><div><label className="field"><span>{ar ? "الاسم الظاهر" : "Display name"}</span><input defaultValue={ar ? "سارة الحربي" : "Sarah Alharbi"} /></label><label className="field"><span>{ar ? "البريد" : "Email"}</span><input value="sarah@nasaq.demo" readOnly /></label><label className="field"><span>{ar ? "المسمى" : "Job title"}</span><input defaultValue={ar ? "قائدة عمليات" : "Operations lead"} /></label></div></div><div className="settings-save-row"><span>{ar ? "تظهر التغييرات في القرارات اللاحقة فقط." : "Changes appear in future decisions only."}</span><button className="button button--primary button--default" type="button" onClick={() => saved(ar ? "حُفظ الملف الشخصي محليًا." : "Profile saved locally.")}><Save size={14} />{ar ? "حفظ التغييرات" : "Save changes"}</button></div></section> : null}
    {section === "preferences" ? <section className="settings-section"><div className="settings-section__head"><span><Languages size={19} /></span><div><h2>{ar ? "التفضيلات" : "Preferences"}</h2><p>{ar ? "لغة الواجهة وكثافتها وطريقة وصول التنبيهات." : "Interface language, density, and notification delivery."}</p></div></div><div className="preference-group"><h3>{ar ? "الواجهة" : "Interface"}</h3><div className="settings-field-row"><span><strong>{ar ? "اللغة الأساسية" : "Primary language"}</strong><small>{ar ? "يمكن التبديل من الشريط العلوي دائمًا." : "You can always switch from the top bar."}</small></span><select defaultValue={locale}><option value="ar">العربية</option><option value="en">English</option></select></div><SettingToggle checked={denseMode} onChange={setDenseMode} label={ar ? "كثافة عالية" : "Dense mode"} detail={ar ? "صفوف أقصر ومساحة أكبر للمحتوى التشغيلي." : "Shorter rows and more room for operational content."} /></div><div className="preference-group"><h3>{ar ? "الإشعارات" : "Notifications"}</h3><SettingToggle checked={approvalAlerts} onChange={setApprovalAlerts} label={ar ? "طلبات الموافقة" : "Approval requests"} detail={ar ? "تنبيه داخل المنتج عند توقف تشغيل ينتظر قرارك." : "In-product alert when a run pauses for your decision."} /><SettingToggle checked={weeklyDigest} onChange={setWeeklyDigest} label={ar ? "ملخص أسبوعي" : "Weekly digest"} detail={ar ? "نشاط المشاريع والتكلفة والتنبيهات المفتوحة." : "Project activity, cost, and open alerts."} /></div><div className="settings-save-row"><span>{ar ? "المعاينة تطبق التبديلات محليًا." : "The preview applies toggles locally."}</span><button className="button button--primary button--default" type="button" onClick={() => saved(ar ? "حُفظت التفضيلات محليًا." : "Preferences saved locally.")}><Save size={14} />{ar ? "حفظ التفضيلات" : "Save preferences"}</button></div></section> : null}
    {section === "workspace" ? <section className="settings-section"><div className="settings-section__head"><span><Users size={19} /></span><div><h2>{ar ? "مساحة العمل" : "Workspace"}</h2><p>{ar ? "الاسم والافتراضيات التي تحكم الموارد الجديدة." : "Name and defaults governing new resources."}</p></div></div><label className="field"><span>{ar ? "اسم المساحة" : "Workspace name"}</span><input defaultValue={ar ? "فريق أفق" : "Horizon Team"} /></label><div className="workspace-policy-list"><div><span><ShieldCheck size={16} /></span><div><strong>{ar ? "الموافقة قبل الأثر الخارجي" : "Approval before external impact"}</strong><p>{ar ? "افتراضي إلزامي لكل وكيل وتدفق جديد." : "Mandatory default for every new agent and flow."}</p></div><Badge tone="success">{ar ? "إلزامي" : "Required"}</Badge></div><div><span><KeyRound size={16} /></span><div><strong>{ar ? "عدم التحول التلقائي بين الدافعين" : "No automatic payer switching"}</strong><p>{ar ? "تعطل BYOK لا يحول التشغيل إلى الرصيد دون سياسة صريحة." : "A BYOK failure never switches to credits without explicit policy."}</p></div><Badge tone="success">{ar ? "محمي" : "Protected"}</Badge></div><div><span><LockKeyhole size={16} /></span><div><strong>{ar ? "أقل صلاحية للمصادر" : "Least privilege for sources"}</strong><p>{ar ? "الوكلاء الجديدة لا ترى مجموعات معرفة حتى تُربط صراحة." : "New agents see no knowledge collections until explicitly linked."}</p></div><Badge tone="success">{ar ? "محمي" : "Protected"}</Badge></div></div><div className="settings-save-row"><span>{ar ? "يتطلب تغيير السياسات دور المسؤول." : "Policy changes require an admin role."}</span><button className="button button--primary button--default" type="button" onClick={() => saved(ar ? "حُفظت سياسة المساحة في المحاكاة." : "Workspace policy saved in the simulation.")}><Save size={14} />{ar ? "حفظ السياسة" : "Save policy"}</button></div></section> : null}
    {section === "providers" ? <section className="settings-section"><div className="settings-section__head"><span><KeyRound size={19} /></span><div><h2>{ar ? "مفاتيح المزودين — BYOK" : "Provider keys — BYOK"}</h2><p>{ar ? "بيانات الاعتماد لا تُعرض مجددًا ولا تغيّر الدافع تلقائيًا." : "Credentials are never shown again and never change the payer automatically."}</p></div><button className="button button--primary button--default" type="button" onClick={() => setProviderOpen(true)}><Plus size={14} />{ar ? "إضافة مفتاح" : "Add key"}</button></div><div className="provider-list"><article><span className="provider-logo">N</span><div><strong>Northstar API</strong><small>{ar ? "Workspace scope · أضيف في ٥ سبتمبر" : "Workspace scope · added Sep 5"}</small></div><span className="masked-key mono">•••• •••• ns_42</span><Badge tone="success">{ar ? "متحقق" : "Verified"}</Badge><button className="icon-button" type="button" aria-label={ar ? "إجراءات Northstar" : "Northstar actions"}><Settings2 size={15} /></button></article>{credentialAdded ? <article><span className="provider-logo">{provider.slice(0,1)}</span><div><strong>{provider} API</strong><small>{ar ? "نطاق مساحة العمل · أضيف الآن" : "Workspace scope · added now"}</small></div><span className="masked-key mono">•••• •••• demo</span><Badge tone="success">{ar ? "تجريبي" : "Demo"}</Badge><button className="icon-button" type="button" aria-label={ar ? `إجراءات ${provider}` : `${provider} actions`}><Settings2 size={15} /></button></article> : null}</div><div className="provider-safety-card"><ShieldCheck size={18} /><div><strong>{ar ? "سلوك المفتاح الآمن" : "Safe key behavior"}</strong><ul><li>{ar ? "لا يعاد المفتاح من API بعد الحفظ." : "The key is never returned by the API after saving."}</li><li>{ar ? "يُسجل النطاق والمزود وحالة الاختبار فقط." : "Only scope, provider, and test status are recorded."}</li><li>{ar ? "الإلغاء يمنع التشغيلات الجديدة فورًا." : "Revocation blocks new runs immediately."}</li></ul></div></div></section> : null}
    {section === "integrations" ? <section className="settings-section"><div className="settings-section__head"><span><Link2 size={19} /></span><div><h2>{ar ? "التكاملات" : "Integrations"}</h2><p>{ar ? "الاتصالات التي قد تنشئ أثرًا خارج مساحة العمل." : "Connections that may create an effect outside the workspace."}</p></div></div><div className="integration-grid">{integrations.map(({ name, detail, connected, icon: Icon }) => <article key={name}><span><Icon size={18} /></span><h3>{name}</h3><p>{detail}</p><Badge tone={connected ? "success" : "neutral"}>{connected ? (ar ? "متصل" : "Connected") : (ar ? "غير متصل" : "Not connected")}</Badge><button className="button button--outline button--compact" type="button">{connected ? (ar ? "إدارة" : "Manage") : (ar ? "مراجعة وتوصيل" : "Review and connect")}</button></article>)}</div><div className="provider-safety-card"><ShieldCheck size={18} /><div><strong>{ar ? "الأثر الخارجي خلف موافقة" : "External effects stay behind approval"}</strong><p>{ar ? "الاتصال وحده لا يمنح الوكلاء حق الإرسال؛ يلزم ربط الأداة وسياسة واضحة." : "Connecting alone does not let agents send; a tool link and explicit policy are still required."}</p></div></div></section> : null}
    {section === "data" ? <section className="settings-section"><div className="settings-section__head"><span><Database size={19} /></span><div><h2>{ar ? "البيانات والخصوصية" : "Data and privacy"}</h2><p>{ar ? "الاحتفاظ والتصدير والحذف بأثر موضح قبل القرار." : "Retention, export, and deletion with impact shown before any decision."}</p></div></div><div className="data-action-list"><article><span><Download size={17} /></span><div><strong>{ar ? "تصدير بيانات المساحة" : "Export workspace data"}</strong><p>{ar ? "المشاريع والمحادثات والتعريفات وسجلات القرارات بصيغة محمولة." : "Projects, conversations, definitions, and decision logs in portable formats."}</p></div><button className="button button--outline button--compact" type="button" onClick={() => saved(ar ? "أُنشئ طلب تصدير تجريبي." : "A demo export request was created.")}>{ar ? "طلب تصدير" : "Request export"}</button></article><article><span><FileClock size={17} /></span><div><strong>{ar ? "سياسة الاحتفاظ" : "Retention policy"}</strong><p>{ar ? "سجلات التشغيل ٣٦٥ يومًا؛ المخرجات حسب المشروع." : "Run records for 365 days; artifacts follow project policy."}</p></div><button className="button button--outline button--compact" type="button">{ar ? "تعديل" : "Edit"}</button></article><article className="is-danger"><span><Trash2 size={17} /></span><div><strong>{ar ? "حذف مساحة العمل" : "Delete workspace"}</strong><p>{ar ? "يتطلب تأكيدًا كتابيًا وإعادة مصادقة ونقل الموارد اللازمة." : "Requires typed confirmation, re-authentication, and required resource transfer."}</p></div><button className="button button--quiet button--compact" type="button">{ar ? "مراجعة الأثر" : "Review impact"}</button></article></div></section> : null}
    {section === "audit" ? <section className="settings-section"><div className="settings-section__head"><span><FileClock size={19} /></span><div><h2>{ar ? "سجل التدقيق" : "Audit log"}</h2><p>{ar ? "قرارات السلطة والسياسات والمفاتيح والتغييرات الحساسة." : "Authority decisions, policies, keys, and sensitive changes."}</p></div><button className="button button--outline button--compact" type="button"><Download size={13} />CSV</button></div><div className="audit-log">{[
      ["09:42:18", ar ? "وافقت سارة على إرسال ملخص الرصد" : "Sarah approved sending the monitoring digest", "approval.approved", "run_weekly_watch"],
      ["09:31:04", ar ? "غيّر يوسف دور مايا إلى منشئ" : "Yousef changed Maya’s role to Builder", "member.role_changed", "mem_maya"],
      ["08:55:40", ar ? "تم التحقق من مفتاح Northstar" : "Northstar key was verified", "credential.verified", "cred_ns_01"],
      ["أمس", ar ? "نُشر الإصدار ٦ من تدفق الرصد" : "Weekly watch flow version 6 published", "flow.published", "flw_weekly_watch"],
    ].map(([time, label, event, resource]) => <div key={event}><span className="mono">{time}</span><i /><span><strong>{label}</strong><small className="mono">{event} · {resource}</small></span><button className="icon-button" type="button" aria-label={ar ? "عرض الحدث" : "View event"}><Eye size={14} /></button></div>)}</div></section> : null}
  </main></div><Dialog.Root open={providerOpen} onOpenChange={setProviderOpen}><Dialog.Portal><Dialog.Overlay className="command-overlay" /><Dialog.Content className="form-dialog provider-dialog" aria-describedby="provider-description"><div className="form-dialog__header"><div><Dialog.Title>{ar ? "إضافة مفتاح مزود" : "Add provider key"}</Dialog.Title><Dialog.Description id="provider-description">{ar ? "يُختبر المفتاح قبل حفظ metadata فقط. لن نعرض قيمته لاحقًا." : "The key is tested before saving metadata only. Its value will not be shown again."}</Dialog.Description></div><Dialog.Close asChild><button className="icon-button" type="button" aria-label={ar ? "إغلاق" : "Close"}><X size={16} /></button></Dialog.Close></div><label className="field"><span>{ar ? "المزود" : "Provider"}</span><select value={provider} onChange={(event) => setProvider(event.target.value)}><option>Northstar</option><option>Vertex Lane</option><option>Cedar Labs</option></select></label><label className="field"><span>{ar ? "مفتاح API" : "API key"}</span><div className="secret-input"><input type={showKey ? "text" : "password"} value={keyValue} onChange={(event) => setKeyValue(event.target.value)} placeholder="sk_demo_••••••••••" autoComplete="off" /><button className="icon-button" type="button" onClick={() => setShowKey((visible) => !visible)} aria-label={showKey ? (ar ? "إخفاء المفتاح" : "Hide key") : (ar ? "إظهار المفتاح" : "Show key")}>{showKey ? <EyeOff size={15} /> : <Eye size={15} />}</button></div></label><label className="field"><span>{ar ? "النطاق" : "Scope"}</span><select defaultValue="workspace"><option value="workspace">{ar ? "مساحة العمل" : "Workspace"}</option><option value="personal">{ar ? "شخصي" : "Personal"}</option></select></label><div className="provider-key-warning"><LockKeyhole size={16} /><p>{ar ? "هذه محاكاة فقط: القيمة لا تغادر المتصفح ولا تُرسل إلى مزود. لا تدخل مفتاحًا حقيقيًا." : "Simulation only: the value never leaves the browser or reaches a provider. Do not enter a real key."}</p></div><div className="form-dialog__actions"><Dialog.Close asChild><button className="button button--quiet button--default" type="button">{ar ? "إلغاء" : "Cancel"}</button></Dialog.Close><button className="button button--primary button--default" type="button" disabled={!keyValue.trim()} onClick={() => { setCredentialAdded(true); setProviderOpen(false); setKeyValue(""); setNotice(ar ? "أضيفت بيانات اعتماد تجريبية دون حفظ قيمة المفتاح." : "Demo credential metadata added without storing the key value."); }}><Check size={14} />{ar ? "اختبار وإضافة تجريبيًا" : "Test and add demo"}</button></div></Dialog.Content></Dialog.Portal></Dialog.Root>{notice ? <DemoToast message={notice} /> : null}</div>;
}
